# Generated by Django 5.2.4 on 2025-08-02 00:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SquareIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("square_access_token", models.TextField(blank=True, null=True)),
                (
                    "square_merchant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "square_environment",
                    models.CharField(default="sandbox", max_length=20),
                ),
                ("is_connected", models.BooleanField(default=False)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("sync_frequency_hours", models.IntegerField(default=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="square_integration",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Square Integration",
                "verbose_name_plural": "Square Integrations",
            },
        ),
        migrations.CreateModel(
            name="SquareLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("square_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="square_locations",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Square Location",
                "verbose_name_plural": "Square Locations",
                "unique_together": {("company", "square_id")},
            },
        ),
        migrations.CreateModel(
            name="SquareInventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("square_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("ITEM", "Item"),
                            ("CATEGORY", "Category"),
                            ("MODIFIER", "Modifier"),
                            ("TAX", "Tax"),
                        ],
                        default="ITEM",
                        max_length=20,
                    ),
                ),
                (
                    "category_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("stock_quantity", models.IntegerField(default=0)),
                ("low_stock_threshold", models.IntegerField(default=0)),
                ("is_available", models.BooleanField(default=True)),
                ("variations", models.JSONField(blank=True, default=list)),
                ("tax_ids", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="square_inventory_items",
                        to="company.company",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="square.squarelocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Square Inventory Item",
                "verbose_name_plural": "Square Inventory Items",
                "ordering": ["name"],
                "unique_together": {("company", "square_id")},
            },
        ),
        migrations.CreateModel(
            name="SquareEmployee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("square_id", models.CharField(max_length=255, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                ("permissions", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="square_employees",
                        to="company.company",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="square.squarelocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Square Employee",
                "verbose_name_plural": "Square Employees",
                "unique_together": {("company", "square_id")},
            },
        ),
        migrations.CreateModel(
            name="SquareOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("square_id", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("COMPLETED", "Completed"),
                            ("CANCELED", "Canceled"),
                            ("DRAFT", "Draft"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "fulfillment_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_date", models.DateTimeField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="square_orders",
                        to="company.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="square.squareemployee",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="square.squarelocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Square Order",
                "verbose_name_plural": "Square Orders",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="SquareOrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.IntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("variations", models.JSONField(blank=True, default=list)),
                ("modifiers", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="square.squareinventoryitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="square.squareorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Square Order Item",
                "verbose_name_plural": "Square Order Items",
            },
        ),
        migrations.CreateModel(
            name="SquareTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("square_id", models.CharField(max_length=255, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELED", "Canceled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("receipt_url", models.URLField(blank=True, null=True)),
                ("source_type", models.CharField(blank=True, max_length=50, null=True)),
                ("order_id", models.CharField(blank=True, max_length=255, null=True)),
                ("transaction_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="square_transactions",
                        to="company.company",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="square.squarelocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Square Transaction",
                "verbose_name_plural": "Square Transactions",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="SquareWebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("payment.created", "Payment Created"),
                            ("payment.updated", "Payment Updated"),
                            ("order.created", "Order Created"),
                            ("order.updated", "Order Updated"),
                            ("inventory.count.updated", "Inventory Count Updated"),
                            ("employee.created", "Employee Created"),
                            ("employee.updated", "Employee Updated"),
                            ("item.created", "Item Created"),
                            ("item.updated", "Item Updated"),
                            ("location.created", "Location Created"),
                            ("location.updated", "Location Updated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("square_id", models.CharField(max_length=255)),
                (
                    "location_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("event_data", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="square_webhook_events",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Square Webhook Event",
                "verbose_name_plural": "Square Webhook Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SquareFinancialSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_refunds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("transaction_count", models.IntegerField(default=0)),
                ("refund_count", models.IntegerField(default=0)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="square_financial_summaries",
                        to="company.company",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_summaries",
                        to="square.squarelocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Square Financial Summary",
                "verbose_name_plural": "Square Financial Summaries",
                "ordering": ["-period_start"],
                "unique_together": {
                    ("company", "location", "period_type", "period_start", "period_end")
                },
            },
        ),
    ]
