# Generated by Django 5.2.4 on 2025-07-27 06:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qb_access_token', models.TextField(blank=True, null=True)),
                ('qb_refresh_token', models.TextField(blank=True, null=True)),
                ('qb_realm_id', models.CharField(blank=True, max_length=255, null=True)),
                ('qb_access_expires_in', models.IntegerField(blank=True, null=True)),
                ('qb_refresh_expires_in', models.IntegerField(blank=True, null=True)),
                ('qb_last_auth', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
