# Generated by Django 5.2.4 on 2025-08-06 00:55

import invitation.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WixWebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("payment.succeeded", "Payment Succeeded"),
                            ("payment.failed", "Payment Failed"),
                            ("order.created", "Order Created"),
                            ("order.updated", "Order Updated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("wix_order_id", models.CharField(max_length=100)),
                (
                    "wix_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payload", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Wix Webhook Log",
                "verbose_name_plural": "Wix Webhook Logs",
                "db_table": "wix_webhook_logs",
            },
        ),
        migrations.CreateModel(
            name="SignupLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "token",
                    models.CharField(
                        default=invitation.models.generate_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("pro", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("wix_order_id", models.CharField(max_length=100, unique=True)),
                (
                    "wix_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(default=invitation.models.get_expiry_date),
                ),
            ],
            options={
                "verbose_name": "Signup Link",
                "verbose_name_plural": "Signup Links",
                "db_table": "signup_links",
                "indexes": [
                    models.Index(fields=["token"], name="signup_link_token_9cd366_idx"),
                    models.Index(fields=["email"], name="signup_link_email_fd0d75_idx"),
                    models.Index(
                        fields=["wix_order_id"], name="signup_link_wix_ord_b3dc83_idx"
                    ),
                ],
            },
        ),
    ]
